CREATE DATABASE FLASHCARD;


USE FLASHCARD;



CREATE TABLE CARDS (
    ID VARCHAR(36) DEFAULT UUID() PRIMARY KEY,
    QUES TEXT NOT NULL,
    ANS TEXT NOT NULL
);

CREATE TABLE ADMIN_USER(
    ADMIN_EMAIL VARCHAR(100) PRIMARY KEY,
    ADMIN_PASSWORD TEXT NOT NULL
); 